import { defineConfig } from 'tsup';

// CSS is imported from src/a11y-css.js (a real JS module generated by
// scripts/build-css.js) instead of a .css file. This bypasses tsup's CSS
// extractor so esbuild bundles the styles inline as a string — no separate
// .css file is emitted and no custom esbuild plugin is needed.
//
// License validation (src/license.js) is NOT bundled here. cdn.jsx loads
// dist/license.min.js at runtime from https://cdn.pigmil.com/a11y/dist/license.min.js
// via a <script> injection so the source stays out of the public repository.
export default defineConfig({
    entry:      { 'a11y.cdn': 'src/cdn.jsx' },
    format:     ['iife'],
    globalName: 'PigmilA11y',   // window.PigmilA11y.mount / .unmount
    outDir:     'dist',
    bundle:     true,
    minify:     true,
    // Remove the default .global suffix tsup adds for IIFE format
    outExtension: () => ({ js: '.js' }),
    // Bundle React + ReactDOM so the script is fully self-contained
    noExternal: ['react', 'react-dom'],
    esbuildOptions(options) {
        options.jsx = 'automatic';
        // Replace Node globals so React works correctly in browser IIFE bundles
        options.define = {
            'process.env.NODE_ENV': '"production"',
        };
    },
});
